package com.dagger_studio.purified.greenDAOGenerated;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dagger_studio.purified.greenDAOGenerated.MyCollectionList;

import com.dagger_studio.purified.greenDAOGenerated.MyCollectionListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCollectionListDaoConfig;

    private final MyCollectionListDao myCollectionListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCollectionListDaoConfig = daoConfigMap.get(MyCollectionListDao.class).clone();
        myCollectionListDaoConfig.initIdentityScope(type);

        myCollectionListDao = new MyCollectionListDao(myCollectionListDaoConfig, this);

        registerDao(MyCollectionList.class, myCollectionListDao);
    }
    
    public void clear() {
        myCollectionListDaoConfig.getIdentityScope().clear();
    }

    public MyCollectionListDao getMyCollectionListDao() {
        return myCollectionListDao;
    }

}
